[tool.poetry]
name = "markup-ai-integration-tests"
version = "0.1.0"
description = "Integration test suite for Markup AI Python SDK"
authors = []
package-mode = false

[tool.poetry.dependencies]
markup-ai-api = { path = "../..", develop = true }  # Use the local version of the SDK
python = ">=3.13.7,<4.0"
pytest = ">=9.0.2"
pytest-bdd = ">=8.1.0"
python-dotenv = ">=1.2.1"
ruff = ">=0.14.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
